#+TITLE: Coders Sanjal
#+OPTIONS: H:1 num:nil toc:nil 
#+AUTHOR: neymarsabin
#+EMAIL: reddevil.sabin@gmail.com


* Introduction 
	A social network developed for developers.It is a platform which intends to be the best junction for all developers mostly of Nepal to meet at a place and discuss,share ideas and collaborate with each other.The social network features include following,story telling,reputation system,real time private messaging,questions and answers by using the forum and many more.

* Configurations 
	#+BEGIN_QUOTE
	Please follow this accordingly in your development environment to setup the system.
	#+END_QUOTE
	Here are the software requirements in the development environment:- 
	1. Ruby-2.4.0p0
	2. Rails 5.0.2
	3. Mysql
	4. Redis [ for future use ]

* Database Configuration: 
	Here is what the *database.yml* file looks like:- 
	#+BEGIN_SRC yaml
  	default: &default
  	adapter: mysql2
  	encoding: utf8
  	pool: 5
  	username: socialnetwork
  	password: socialnetwork
  	host: localhost

  	development:
  		<<: *default
  		database: socialnetwork_development

  	test:
  		<<: *default
  		database: socialnetwork_test
	#+END_SRC



** Start by creating database:
	 #+BEGIN_SRC sh 
	 rails db:create
	 #+END_SRC

	 
** Check in mysql console before performing these actions: 
*** create a mysql user as socialnetwork
		create a user *socialnetwork* for the database *socialnetwork_development*:- 
		#+BEGIN_SRC sql 
    	grant all privileges on socialnetwork_development.* to 'socialnetwork'@'localhost' identified by 'socialnetwork';
		#+END_SRC
		and similarly for the database *socialnetwork_test*:- 
		#+BEGIN_SRC sql 
		grant all privileges on socialnetwork_test.* to 'socialnetwork'@'localhost' identified by 'socialnetwork';
		#+END_SRC

*** check if the user has been created:- 
		#+BEGIN_SRC sh 
		mysql -u socialnetwork -p
		#+END_SRC
		Note the password is *socialnetwork* for both *development* and *test* environments.
		

** Now migrate the database: 
	 In your console:
	 #+BEGIN_SRC sh 
	 rails db:migrate
	 #+END_SRC

* To contribute
	Just create a new branch and do your changes.Just for the note: 
	#+BEGIN_QUOTE
	Always be synced up with the github master branch.None will be responsible for your merge conflicts.
	#+END_QUOTE
	To pull the master branch: 
	#+BEGIN_SRC sh 
	git pull origin master
	#+END_SRC
	After your contributions just push it or create a pull request.

* Thank You Team Members
	#+BEGIN_QUOTE
	Follow these and we all be together in the project.
	#+END_QUOTE
